services:
  flux-dev-worker:
    image: flux-dev-worker:dev
    pull_policy: never
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - RUN_MODE=local-api
    ports:
      - "8000:8000"
    volumes:
      - ./data/runpod-volume:/runpod-volume
